ShiraTheMogul/jep-hack

- data/pokemon/base_stats/balumba.asm
- data/pokemon/base_stats/blottle.asm
- data/pokemon/base_stats/burgela.asm
- data/pokemon/base_stats/cheep.asm
- data/pokemon/base_stats/croakozuna.asm
- data/pokemon/base_stats/disturban.asm
- data/pokemon/base_stats/dodaerie.asm
- data/pokemon/base_stats/gavillain.asm
- data/pokemon/base_stats/grimera.asm
- data/pokemon/base_stats/guardia.asm
- data/pokemon/base_stats/jabetta.asm
- data/pokemon/base_stats/jungela.asm
- data/pokemon/base_stats/kolta.asm
- data/pokemon/base_stats/magnetite.asm
- data/pokemon/base_stats/magnezone.asm
- data/pokemon/base_stats/marowaka.asm
- data/pokemon/base_stats/muka.asm
- data/pokemon/base_stats/pendraken.asm
- data/pokemon/base_stats/ponytag.asm
- data/pokemon/base_stats/ramoose.asm
- data/pokemon/base_stats/rapidashg.asm
- data/pokemon/base_stats/ribbito.asm
- data/pokemon/base_stats/slowbrog.asm
- data/pokemon/base_stats/slowkingg.asm
- data/pokemon/base_stats/slowpokeg.asm
- data/pokemon/base_stats/smujj.asm
- data/pokemon/base_stats/tangrowth.asm
- data/pokemon/base_stats/walkingwake.asm
- data/pokemon/base_stats/weezingg.asm
A bunch of base stat ASMs, up to Disturban! Also includes Walking Wake!
> Base Stat Batch 4

- data/pokemon/base_stats/aercrow.asm
- data/pokemon/base_stats/belledam.asm
- data/pokemon/base_stats/bipulla.asm
- data/pokemon/base_stats/calflac.asm
- data/pokemon/base_stats/dudunsparce.asm
- data/pokemon/base_stats/farigiraf.asm
- data/pokemon/base_stats/mismagius.asm
- data/pokemon/base_stats/moibelle.asm
- data/pokemon/base_stats/phandarin.asm
- data/pokemon/base_stats/stromen.asm
- data/pokemon/base_stats/ursaluna.asm
11 new Base Stat files in order to prepare for additions up to Violet City!
> ASM Batch 6

- data/pokemon/base_stats/bonsly.asm
- data/pokemon/base_stats/caretorker.asm
- data/pokemon/base_stats/honchkrow.asm
- data/pokemon/base_stats/wyrdeer.asm
A couple of base stat asms, will def do more work on this next batch soon, just had a rough day today. Will be back at it with a big commit HOPEFULLY tomorrow but with all due effort to get it out this week :D
> Some Light Prep

- data/pokemon/dex_entries/bonsly.asm
- data/pokemon/dex_entries/caretorker.asm
- data/pokemon/dex_entries/elebebi.asm
- data/pokemon/dex_entries/electivire.asm
- data/pokemon/dex_entries/guardia.asm
- data/pokemon/dex_entries/happiny.asm
- data/pokemon/dex_entries/honchkrow.asm
- data/pokemon/dex_entries/iguanarch.asm
- data/pokemon/dex_entries/magmortar.asm
- data/pokemon/dex_entries/mime_jr_.asm
- data/pokemon/dex_entries/mimmeo.asm
- data/pokemon/dex_entries/ministare.asm
- data/pokemon/dex_entries/porygon_z.asm
- data/pokemon/dex_entries/smujj.asm
- data/pokemon/dex_entries/squeamata.asm
- data/pokemon/dex_entries/wyrdeer.asm
Adds dex entries for the upcoming mon additions! Includes accurate heights and weights for all mons, as well as estimated ones for newcomers. Feel free to check my work there!
> A Bunch of Cool Dex Entries!!!

- data/pokemon/evos_attacks_johto.asm
- data/pokemon/evos_attacks_kanto.asm
- data/wild/johto_grass.asm
Quick feedback changes from PvK's playthrough.
- Changed Stromen from Sprout Tower to Burned Tower, for more thematic fit (and balance dear god) 
- Gave Moibelle Bite at Level 10 and moved some learn levels
- Switched Pay Day to Level 5 in Coinpur's learnset, and shifted levels down to accomodate
> Quick Feedback Changes

- data/pokemon/evos_attacks_johto.asm
I can't believe I made this error. I'm a fool.
Ampharos' Hypnosis learn level has been changed from 58 to 56.
How could I have made this mistake. I hope you forgive me.
> The Worst Mistake I've Ever Made

- audio.asm
Linux is case sensitive whereas windows is not so this was breaking the build
> fixed case sensitivity

- audio.asm
- audio/music/ColdWinter.asm
- audio/music/CoolCave.asm
- audio/music_pointers.asm
- constants/music_constants.asm
This should do the trick. Here are the two new themes, tentatively named:
- ColdWinter
- CoolCave
(I am terrible with naming my tracks, read the description in the music files for better context)
> Two new themes!

- data/pokemon/evos_attacks_kanto.asm
Updated Pidgeot's moveset! Because lord knows it needed it.
> Quick Pidgeot Buffs

- audio.asm
- audio/music/NihonTrainerBattle.asm
- audio/music/NorthCity.asm
- audio/music_pointers.asm
- constants/music_constants.asm
The North City theme is here!
Additionally, the generic Nihon Trainer battle theme.
Read the headers of the files for more information.
> North City and Nihon Trainer Battle

- audio.asm
- audio/music/Tanoby01.asm
- audio/music_pointers.asm
- constants/music_constants.asm
Here it is! As always, check the header in the song file for more details.
Crazy how these recent leaks spark creativity, huh?
> The Tanoby Ruins theme

- data/types/type_matchups.asm
Same as KEP-Hack, adjusts Fairy's type chart to account for new oldest known revision.
> Fairy Type Rework

- audio.asm
- audio/music/CoralCity.asm
- audio/music/CrystalCrater.asm
- audio/music/NihonTime.asm
- audio/music_pointers.asm
- constants/music_constants.asm
Here it is.
I'm probably taking a small break after this one, I'm sure you understand!
> Deep in the Crater

- audio.asm
1000 GIGABYTES MORE RAM TO LUCI
> Fix Audio.asm bank

- audio.asm
- audio/music/AlphalithBattle.asm
- audio/music/FloodedShrine.asm
- audio/music_pointers.asm
- constants/music_constants.asm
The soundscape for the pillar hugging creatura
Encounter theme SoonTM I promise
> The Alphalith Package

- audio.asm
- audio/music/Fortuna.asm
- audio/music_pointers.asm
- constants/music_constants.asm
I heard that you like jamming the hell out while getting absolutely destroyed by giant birds and fire breathing dragons!
> Fortuna type beat

- data/pokemon/evos_attacks_kanto.asm
- maps/DebugRoom.asm
First commit in a LONG time, it's good to be back :3
> Shellder Additions

- audio.asm
- audio/music/JasperForest.asm
- audio/music_pointers.asm
- constants/music_constants.asm
The 3 month dry streak is OVER
> Jasper Forest(very spooky)

- data/trainers/parties.asm
> Bug Catcher Fix

- data/trainers/parties.asm
Jasmine's Sharpoon's level was still being read by the game and attempting to send out nothing as a result.
> Commented out the Inivisible Sharpoon.
